name = "piston-proxy-bot"
main = "./src/server.ts"
compatibility_date="2024-11-11"

# [secrets]
# DISCORD_TOKEN
# DISCORD_PUBLIC_KEY
# DISCORD_APPLICATION_ID
# PROXY_API_URL

[observability.logs]
enabled = true
invocation_logs = true
