on:
  push:
    branches:
      - main
  pull_request:
name: ci
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v5
        with:
          node-version: lts/*
      - uses: pnpm/action-setup@v4
        with:
          version: latest
      - run: pnpm install
      - run: pnpm run lint
